### ISSUE TITLE
Not compatible with Rails 4.2

### ISSUE THREAD

**Issue by marksiemers** [sibext/rails_admin_enum4#1]
When trying to bundle install this gem, it won't work with Rails 4.2:

```
rails_admin_enum4 (>= 0) ruby depends on
      rails (~> 4.1.0) ruby
```

**Comment by moskvin** [comment]
Should be fixed by https://github.com/sibext/rails_admin_enum4/commit/cb504520fbdb29718099cc1b355f849204283075
